name: sms_auto_sender
description: Flutter version of SMS Auto Sender
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

  # v2 embedding fork for SMS
  sms_advanced:
    git:
      url: https://github.com/fluttercommunity/sms_advanced_v2.git

  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2

  # v2 embedding fork for foreground service
  flutter_foreground_task:
    git:
      url: https://github.com/fysoul17/flutter_foreground_task.git
      ref: main